### ISSUE TITLE
Wrong path to cache dir will hang the plugin

### ISSUE THREAD

**Issue by FrankHossfeld** [Vertispan/j2clmavenplugin#24]
Use a wrong path for the  gwt3 cache dir (f.e.: `/home/myusername/.m2/gwt3BuildCache`).

Now, run `mvn j2cl:clean`or `mvn j2cl:test`.  

The plugin will stop working after a few seconds and without ereturining the control to Maven.

**Comment by niloc132** [comment]
I think this may be fixed with the j2cl:clean bugfix (#28), can you confirm?

**Comment by FrankHossfeld** [comment]
yes, it is fixed.
