### ISSUE TITLE
Transpiler encoding warning

### ISSUE THREAD

**Issue by stockiNail** [Vertispan/j2clmavenplugin#31]
Using the plugin,  it seems J2CL transpiler is using the default encoding of JVM and there isn't any parameter to pass in order to use another charset. 

This generates some warnings if java source code contains some UTF-8 chars not compliant with JVM encoding.

Setting the file.encoding=UTF-8 to JVM (when run), it works without any warning.

**Comment by niloc132** [comment]
It looks like closure-compiler also assumes utf-8 https://github.com/google/closure-compiler/issues/3556.

Another kinda-related "here's what closure assumes about your code" issue https://github.com/google/closure-compiler/issues/3555

**Comment by niloc132** [comment]
J2cl already hardcodes utf-8 in at least one place when parsing the input .java files into JDT:
https://github.com/google/j2cl/blob/master/transpiler/java/com/google/j2cl/frontend/jdt/JdtParser.java#L119 - but as you can see, there is a typo there, it should be `UTF-8`, not `UTF_8`. There is also another issue where js content is written to disk using the system charset, I'm correcting both of these in a patch to upstream j2cl. https://github.com/google/j2cl/pull/84

Note that this doesn't close the issue! The logged warning that you see is actually from javac itself, not j2cl, and we need to tell javac to also force the use of utf-8.

**Comment by niloc132** [comment]
Fixed by ca176a78ec7f2e60b8f5bdb8a55e853c2caa980d
