### ISSUE TITLE
plugin shows error when running 'j2cl:clean' and the 'gwt3-cache-dir' does not exist

### ISSUE THREAD

**Issue by FrankHossfeld** [Vertispan/j2clmavenplugin#37]
Steps to reproduce:

* set up Maven settings to use the `gwt3-cache-dir`
* delete the `gwt3-cache-dir`
* run `mvn j2cl:clean`

ends in the following error:
`Failed to execute goal com.vertispan.j2cl:j2cl-maven-plugin:0.13-SNAPSHOT:clean (default-cli) on project gwt-aria-j2cl-tests: /Users/hoss/.m2/gwt3-cache-dir/0.13-SNAPSHOT`

**Comment by niloc132** [comment]
I am pretty sure this is fixed, Frank can you still reproduce this?

**Comment by FrankHossfeld** [comment]
Looks like it is fixed:
```
[INFO] Directory doesn't exist, nothing to clean: /Users/hoss/.m2/gwt3-cache-dir/0.15-SNAPSHOT
````
