### ISSUE TITLE
Copy static resources under `public` folder from dependencies

### ISSUE THREAD

**Issue by vegegoku** [Vertispan/j2clmavenplugin#39]
In gwt we used to have a public folder in dependencies and when the app is compiled the content of the public folder is copied to the application.

How can we achieve this in j2cl maven plugin and what would be the solution?

**Comment by TDesjardins** [comment]
I currently I came across the same question while migrating gwt-core tests to J2CL. I solved this issue by simply using `copy-resources`-goal of `maven-resources-plugin`. As far as I know there isn't a built in solution yet.
